apiVersion: v1
kind: Secret
metadata:
  namespace: workshop
  name: mongo-sec
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= #password123    #echo 'cGFzc3dvcmQxMjM=' | base64 --decode -> to decode password
  username: YWRtaW4=         #admin
