apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: workshop
  labels:
    app: frontend
spec:
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
